#!/usr/bin/env ruby

require 'uri'

# git@github.com:atsuya/commithub-client.git
# git@github.com:1234/atsuya/commithub-client.git
# ssh://atsuya@pictshare.me:2564/var/repositories/git/loketan
# file:///Users/atsuya/Development/nodejs/commithub-client

result = nil

if ARGV.length == 1
  target = ARGV[0]
  if target.match(/^.+\:\d+\/.*$/)
    puts 'special case, adding http://'
    target = 'http://' + target
  end

  # try parsing as if it is url
  begin
    segments = URI.parse(target)
    result = segments.path
  rescue URI::InvalidURIError => exception
    puts 'oops'
  end
else
  puts 'needs one parameter'
end

if result
  puts result
  exit 0
else
  exit 1
end
